server:
  port: 10008
spring:
  data:
    mongodb:
      uri: mongodb://localhost/gsite
      host: localhost
  mvc:
    view:
      prefix:
        /
      suffix:
        .html

endpoints:
  cors:
    allowed-headers: '*'
    allowed-origins: '*'
    allowed-methods: '*'